// <auto-generated />
using System;
using BancoZeneide.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BancoZeneide.Migrations
{
    [DbContext(typeof(BancoZeneideContext))]
    [Migration("20201202181516_OrtherEntities")]
    partial class OrtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BancoZeneide.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NivelCategoria");

                    b.Property<string>("NomeCategoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("BancoZeneide.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Cnpj");

                    b.Property<string>("Cpf");

                    b.Property<string>("Email");

                    b.Property<string>("Endereco");

                    b.Property<string>("Estado");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BancoZeneide.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int?>("CategoriaIdCategoria");

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("DataVenda");

                    b.Property<int?>("PetIdPet");

                    b.Property<int>("QuantidadeItensComprada");

                    b.Property<double>("ValorTotal");

                    b.Property<int?>("VendedorIdVendedor");

                    b.HasKey("PedidoId");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PetIdPet");

                    b.HasIndex("VendedorIdVendedor");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("BancoZeneide.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Peso");

                    b.Property<string>("Raca");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("IdPet");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("BancoZeneide.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoriaIdCategoria");

                    b.Property<string>("Descricao");

                    b.Property<string>("NomeProduto");

                    b.Property<int?>("PedidoId");

                    b.Property<double>("ValorProduto");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("BancoZeneide.Models.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CpfVendedor");

                    b.Property<DateTime>("DataInicio");

                    b.Property<string>("NomeVendedor");

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("BancoZeneide.Models.Pedido", b =>
                {
                    b.HasOne("BancoZeneide.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("BancoZeneide.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("BancoZeneide.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetIdPet");

                    b.HasOne("BancoZeneide.Models.Vendedor", "Vendedor")
                        .WithMany("Pedido")
                        .HasForeignKey("VendedorIdVendedor");
                });

            modelBuilder.Entity("BancoZeneide.Models.Pet", b =>
                {
                    b.HasOne("BancoZeneide.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("BancoZeneide.Models.Produto", b =>
                {
                    b.HasOne("BancoZeneide.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("BancoZeneide.Models.Pedido")
                        .WithMany("Produto")
                        .HasForeignKey("PedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
